73PageModel/Models/Product.cs
public class Product
{
    public int id { get; set; }
    public string name { get; set; }
    public string Description { get; set; }
    public Decimal Price { get; set; }
}

73PageModel/Models/UserContact.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

public class UserContact
{
    // Chỉ hỗ trợ phương thức 'Post'
    // [BindProperty(SupportsGet = true)]
    [BindProperty]
    [DisplayName("ID của bạn:")]
    [Range(1,10, ErrorMessage = "nhập sai")]
    public int UserId {get;set;} 
    [BindProperty]
    [DisplayName("Email Của bạn:")]
    [EmailAddress(ErrorMessage = "Nhập sai email")]
    public string Email {get;set;}
    [BindProperty]
    [DisplayName("Tên người dùng:")]
    public string UserName {get;set;}
}

73PageModel/Pages/ContactRequest.cshtml.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

public class ContactRequestModel : PageModel
{
    [BindProperty]
    public UserContact userContact { get; set; }

    private readonly ILogger<ContactRequestModel> logger;
    public ContactRequestModel(ILogger<ContactRequestModel> _logger)
    {
        logger = _logger;
        logger.LogInformation("Init Contact..");
    }

    public void OnPost()
    {
        Console.WriteLine(userContact.Email);
    }
}

73PageModel/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _73PageModel.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

73PageModel/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _73PageModel.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

73PageModel/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _73PageModel.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

73PageModel/Pages/ProductPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _73PageModel.Pages
{
    public class ProductPageModel : PageModel
    {
        private readonly ILogger<ProductPageModel> logger;
        public readonly ProductService productService;
        public Product product { get; set; }
        public ProductPageModel(ILogger<ProductPageModel> _logger, ProductService productService)
        {
            logger = _logger;
            this.productService = productService;
        }
        // tự động tìm trên url xem có trường 'id' không, nếu có thì tự động gán vào id
        // [FromQuery]
        public void OnGet([FromRoute(Name = "id")]int? id, [Bind("Id","Name")]Product sanpham)
        {
            Console.WriteLine($"ID: {sanpham.id}");
            Console.WriteLine($"Name: {sanpham.name}");

            // var data =this.Request.Form["id"];
            // var data =this.Request.Query["id"];
            // var data =this.Request.RouteValues["id"];
            // var data =this.Request.Headers["id"];

            var data = this.Request.RouteValues["id"];
            if (data != null)
            {
                Console.WriteLine(data.ToString());
            }

            if (id != null)
            {
                ViewData["Title"] = $"Sản phẩm có id = {id}";
                product = productService.FindProduct(id.Value);
            }
            else
            {
                ViewData["Title"] = $"Danh sách sản phẩm";
            }
        }
        // /product/{id:int?}?handle=LastProduct
        public IActionResult OnGetLastProduct()
        {
            ViewData["Titile"] = "san pham cuoi";
            product = productService.AllProduct().LastOrDefault();
            if (product != null)
            {
                return Page();
            }
            else
            {
                // return NotFound();
                return Content("không tìm thấy sản phẩm");
            }

        }

        public IActionResult OnGetRemoveAll()
        {
            productService.AllProduct().Clear();
            return RedirectToPage("ProductPage");
        }


        public IActionResult OnGetLoad()
        {
            productService.LoadProduct();
            return RedirectToPage("ProductPage");
        }

        public IActionResult OnPostDelete(int? id)
        {
            if (id != null)
            {
                product = productService.FindProduct(id.Value);
                if (product != null)
                {
                    productService.AllProduct().Remove(product);
                }
            }
            return this.RedirectToPage("ProductPage", new { id = string.Empty });
        }
    }
}

73PageModel/Pages/ContactRequest.cshtml
@page "/contact"
@model ContactRequestModel

<h1 class="display-4">trang lien he</h1>
<p class="lead">dien cac thong tin lien he</p>

<form class="bg-light p-2 m-2" method="Post" asp-page="ContactRequest">
    <div class="mb-3">
        <label class="form-label" asp-for="userContact.UserId"></label>
        <input class="form-control" asp-for="userContact.UserId" />
        <span class="text-danger" asp-validation-for="userContact.UserId"></span>
    </div>
        <div class="mb-3">
        <label class="form-label" asp-for="userContact.Email"></label>
        <input class="form-control" asp-for="userContact.Email" />
        <span class="text-danger" asp-validation-for="userContact.Email"></span>
    </div>
        <div class="mb-3">
        <label class="form-label" asp-for="userContact.UserName"></label>
        <input class="form-control" asp-for="userContact.UserName" />
        @* <span class="text-danger" asp-validation-for="UserId"></span> *@
    </div>
    <button class="btn btn-danger" type="submit">Send</button>
</form>

<div class="alert alert-danger">
    <p>thông tin user</p>
    <ul>
        <li>User ID: @Model.userContact.UserId</li>
        <li>Email: @Model.userContact.Email</li>
        <li>User Name: @Model.userContact.UserName</li>
    </ul>
</div>


@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

73PageModel/Pages/ProductPage.cshtml
@page "/product/{id:int?}"
@model _73PageModel.Pages.ProductPageModel
@{
    var product = Model.product;
    var products = Model.productService.AllProduct();
}

<h1>@ViewData["Title"]</h1>
@if (product != null)
{
    <h2>@product.name</h2>
    <p>@product.Description</p>
    <p><a asp-page="ProductPage" asp-route-id="">Danh Sách sản phẩm</a>
    <form method="post" asp-page="ProductPage" asp-page-handler="Delete" asp-route-id="@product.id">
        <button type="submit" class="btn btn-danger">xoá</button>
    </form>
    </p>
}
else
{
    <ul>
        @foreach (var item in products)
        {
            <li>
                <a asp-page="ProductPage" asp-route-id="@item.id">@item.name</a>

            </li>
        }
    </ul>
    <hr>
    <p>
        <a class="btn btn-primary" asp-page="ProductPage" asp-page-handler="LastProduct">
            Sản phẩm cuối
        </a>
        <a class="btn btn-danger" asp-page="ProductPage" asp-page-handler="RemoveAll">
            xoá toàn bộ sản phẩm
        </a>
        <a class="btn btn-primary" asp-page="ProductPage" asp-page-handler="Load">
            Nạp lại SP
        </a>
    </p>
}